# Backend configuration for GitHub
backend:
  name: github
  repo: inikknbedalo/bedalo
  branch: main
  base_url: https://bedalo.pages.dev
  auth_endpoint: /api/auth

# Media files will be stored in the source directory to be processed by Astro
media_folder: "src/assets/images"
public_folder: "/assets/images"

# A single collection to manage all static pages
collections:
  - name: "halaman"
    label: "Manajemen Halaman"
    description: "✍️ Kelola konten untuk semua halaman statis di website ini."
    files:
      # ===================================================================
      # 1. Halaman: Beranda
      # ===================================================================
      - file: "src/data/index.json"
        label: "🏠 Beranda"
        name: "beranda"
        fields:
          - name: "hero"
            label: "Hero Section"
            widget: "object"
            fields:
              - { label: "Teks Alternatif Gambar", name: "imageAlt", widget: "string" }
              - { label: "Judul", name: "judul", widget: "string" }
              - { label: "Subjudul", name: "subjudul", widget: "string" }

          - name: "profilSingkat"
            label: "Profil Singkat Kepala Dusun"
            widget: "object"
            fields:
              - { label: "Foto Kepala Dusun", name: "fotoUrl", widget: "image" }
              - { label: "Nama Kepala Dusun", name: "namaKepalaDusun", widget: "string" }
              - { label: "Jabatan", name: "jabatan", widget: "string" }
              - name: "sambutan"
                label: "Sambutan (per paragraf)"
                widget: "list"
                field: { label: "Paragraf", name: "paragraf", widget: "text" }

          - name: "potensiUnggulan"
            label: "Potensi Unggulan"
            widget: "list"
            summary: "{{fields.judul}}"
            fields:
              - { label: "Judul", name: "judul", widget: "string" }
              - { label: "Deskripsi", name: "deskripsi", widget: "text" }
              - { label: "Link Halaman", name: "link", widget: "string" }

          - name: "pariwisata"
            label: "Seksi Pariwisata"
            widget: "object"
            fields:
              - { label: "Deskripsi", name: "deskripsi", widget: "text" }
              - name: "gambar"
                label: "Gambar Pariwisata"
                widget: "list"
                summary: "{{fields.alt}}"
                fields:
                  - { label: "Gambar", name: "url", widget: "image" }
                  - { label: "Teks Alternatif", name: "alt", widget: "string" }

          - name: "galeri"
            label: "Seksi Galeri"
            widget: "list"
            summary: "{{fields.alt}}"
            fields:
              - { label: "Gambar", name: "url", widget: "image" }
              - { label: "Teks Alternatif", name: "alt", widget: "string" }

      # ===================================================================
      # 2. Halaman: Profil
      # ===================================================================
      - file: "src/data/profil.json"
        label: "🏛️ Profil"
        name: "profil"
        fields:
          - name: "sejarah"
            label: "Sejarah (per paragraf)"
            widget: "list"
            field: { label: "Paragraf", name: "paragraf", widget: "text" }

          - name: "visiMisi"
            label: "Visi & Misi"
            widget: "object"
            fields:
              - { label: "Visi", name: "visi", widget: "string" }
              - name: "misi"
                label: "Misi"
                widget: "list"
                field: { label: "Poin Misi", name: "misi_item", widget: "string" }

          - name: "strukturPemerintahan"
            label: "Struktur Pemerintahan"
            widget: "list"
            summary: "{{fields.nama}} - {{fields.jabatan}}"
            fields:
              - { label: "Foto", name: "fotoUrl", widget: "image" }
              - { label: "Nama", name: "nama", widget: "string" }
              - { label: "Jabatan", name: "jabatan", widget: "string" }

          - name: "demografi"
            label: "Demografi"
            widget: "object"
            fields:
              - { label: "Jumlah Penduduk", name: "jumlahPenduduk", widget: "string" }
              - { label: "Laki-laki", name: "lakiLaki", widget: "string" }
              - { label: "Perempuan", name: "perempuan", widget: "string" }
              - name: "mataPencaharian"
                label: "Mata Pencaharian"
                widget: "list"
                field: { label: "Jenis Pekerjaan", name: "pekerjaan", widget: "string" }

          - name: "petaUrl"
            label: "URL Peta Google Maps (Embed)"
            widget: "string"

      # ===================================================================
      # 3. Halaman: Potensi
      # ===================================================================
      - file: "src/data/potensi.json"
        label: "✨ Potensi"
        name: "potensi"
        fields:
          - name: "umkm"
            label: "UMKM & Produk Lokal"
            widget: "list"
            summary: "{{fields.judul}}"
            fields:
              - { label: "Gambar Produk", name: "gambarUrl", widget: "image" }
              - { label: "Teks Alternatif", name: "altText", widget: "string" }
              - { label: "Nama Produk", name: "judul", widget: "string" }
              - { label: "Deskripsi", name: "deskripsi", widget: "text" }
              - { label: "Harga", name: "harga", widget: "string" }
              - { label: "Link Kontak (WA)", name: "kontakLink", widget: "string" }

          - name: "pertanian"
            label: "Pertanian"
            widget: "object"
            fields:
              - { label: "Gambar Utama", name: "gambarUrl", widget: "image" }
              - { label: "Teks Alternatif", name: "altText", widget: "string" }
              - { label: "Judul", name: "judul", widget: "string" }
              - { label: "Deskripsi", name: "deskripsi", widget: "text" }
              - name: "komoditas"
                label: "Daftar Komoditas"
                widget: "list"
                summary: "{{fields.nama}}"
                fields:
                  - { label: "Nama Komoditas", name: "nama", widget: "string" }
                  - { label: "Ikon (Font Awesome Class)", name: "icon", widget: "string" }

          - name: "lainnya"
            label: "Potensi Lainnya"
            widget: "list"
            summary: "{{fields.judul}}"
            fields:
              - { label: "Ikon (Font Awesome Class)", name: "icon", widget: "string" }
              - { label: "Judul", name: "judul", widget: "string" }
              - { label: "Deskripsi", name: "deskripsi", widget: "text" }
      
      # ===================================================================
      # 4. Halaman: Pariwisata
      # ===================================================================
      - file: "src/data/pariwisata.json"
        label: "🏖️ Pariwisata"
        name: "pariwisata"
        fields:
          - name: "destinasi"
            label: "Destinasi Wisata"
            widget: "list"
            summary: "{{fields.judul}}"
            fields:
              - { label: "Gambar", name: "gambarUrl", widget: "image" }
              - { label: "Alt Text", name: "altText", widget: "string" }
              - { label: "Judul", name: "judul", widget: "string" }
              - { label: "Deskripsi", name: "deskripsi", widget: "text" }
              - { label: "Link Peta", name: "petaLink", widget: "string" }

          - name: "tradisi"
            label: "Tradisi"
            widget: "list"
            summary: "{{fields.judul}}"
            fields:
              - { label: "Gambar", name: "gambarUrl", widget: "image" }
              - { label: "Alt Text", name: "altText", widget: "string" }
              - { label: "Judul", name: "judul", widget: "string" }
              - name: "deskripsi"
                label: "Deskripsi (per paragraf)"
                widget: "list"
                field: { label: "Paragraf", name: "paragraf", widget: "text" }

          - name: "kesenian"
            label: "Kesenian"
            widget: "list"
            summary: "{{fields.judul}}"
            fields:
              - { label: "Gambar", name: "gambarUrl", widget: "image" }
              - { label: "Alt Text", name: "altText", widget: "string" }
              - { label: "Judul", name: "judul", widget: "string" }
              - name: "deskripsi"
                label: "Deskripsi (per paragraf)"
                widget: "list"
                field: { label: "Paragraf", name: "paragraf", widget: "text" }

          - name: "kalender"
            label: "Kalender Acara"
            widget: "list"
            summary: "{{fields.acara}}"
            fields:
              - { label: "Acara", name: "acara", widget: "string" }
              - { label: "Deskripsi", name: "deskripsi", widget: "string" }
              - { label: "Tanggal", name: "tanggal", widget: "string" }

      # ===================================================================
      # 5. Halaman: Galeri
      # ===================================================================
      - file: "src/data/galeri.json"
        label: "🖼️ Galeri"
        name: "galeri"
        fields:
          - name: "foto"
            label: "Galeri Foto"
            widget: "list"
            summary: "{{fields.alt}}"
            fields:
              - { label: "Gambar", name: "url", widget: "image" }
              - { label: "Keterangan (Alt Text)", name: "alt", widget: "string" }
          
          - name: "video"
            label: "Galeri Video"
            widget: "list"
            summary: "{{fields.judul}}"
            fields:
              - { label: "URL Embed Video", name: "url", widget: "string", hint: "Contoh: https://www.youtube.com/embed/xxxxx" }
              - { label: "Judul Video", name: "judul", widget: "string" }

      # ===================================================================
      # 6. Halaman: Kontak
      # ===================================================================
      - file: "src/data/kontak.json"
        label: "📞 Kontak"
        name: "kontak"
        fields:
          - name: "kontakPemerintah"
            label: "Kontak Perangkat Dusun"
            widget: "list"
            summary: "{{fields.nama}} - {{fields.jabatan}}"
            fields:
              - { label: "Foto", name: "fotoUrl", widget: "image" }
              - { label: "Nama", name: "nama", widget: "string" }
              - { label: "Jabatan", name: "jabatan", widget: "string" }
              - { label: "Telepon", name: "telepon", widget: "string" }

          - name: "formAspirasi"
            label: "Form Aspirasi"
            widget: "object"
            fields:
              - { label: "Judul", name: "judul", widget: "string" }
              - { label: "Deskripsi", name: "deskripsi", widget: "text" }
              - { label: "URL Action Formulir", name: "formActionUrl", widget: "string" }
              - name: "entry"
                label: "Entry Mapping (Google Form)"
                widget: "object"
                fields:
                  - { label: "Nama Field 'Nama'", name: "nama", widget: "string" }
                  - { label: "Nama Field 'Kontak'", name: "kontak", widget: "string" }
                  - { label: "Nama Field 'Subjek'", name: "subjek", widget: "string" }
                  - { label: "Nama Field 'Pesan'", name: "pesan", widget: "string" }

      # ===================================================================
      # 7. Halaman: Tentang KKN
      # ===================================================================
      - file: "src/data/tentang-kkn.json"
        label: "🎓 Tentang KKN"
        name: "kkn"
        fields:
          - name: "judulHalaman"
            label: "Judul Halaman"
            widget: "object"
            fields:
              - { label: "Judul", name: "judul", widget: "string" }
              - { label: "Universitas", name: "universitas", widget: "string" }
          
          - name: "pengantar"
            label: "Pengantar"
            widget: "object"
            fields:
              - { label: "Judul", name: "judul", widget: "string" }
              - { label: "Deskripsi", name: "deskripsi", widget: "text" }

          - name: "anggota"
            label: "Anggota Tim KKN"
            widget: "object"
            fields:
              - { label: "Judul Seksi", name: "judul", widget: "string" }
              - name: "tim"
                label: "Daftar Anggota"
                widget: "list"
                summary: "{{fields.nama}} - {{fields.prodi}}"
                fields:
                  - { label: "Foto", name: "fotoUrl", widget: "image" }
                  - { label: "Nama", name: "nama", widget: "string" }
                  - { label: "Prodi", name: "prodi", widget: "string" }
                  - { label: "URL Instagram (opsional)", name: "instagramUrl", widget: "string", required: false }